# Generated by Django 4.1.5 on 2023-02-01 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('players', models.CharField(max_length=30)),
                ('playingTime', models.CharField(max_length=30)),
                ('bgg', models.CharField(max_length=1000)),
                ('year', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('icon', 'icon'), ('banner', 'banner'), ('example', 'example'), ('cover', 'cover')], max_length=20)),
                ('image', models.ImageField(default=None, upload_to='images/')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Icon Legend', 'Icon Legend'), ('Turn Order', 'Turn Order')], max_length=20)),
                ('hashid', models.CharField(choices=[('legend', 'legend'), ('turn', 'turn')], max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='geeks.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geeks.image'),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('image', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='geeks.image')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='geeks.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
