# Generated by Django 4.1.5 on 2023-01-30 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(default=None, upload_to='images/')),
                ('players', models.CharField(max_length=30)),
                ('playingTime', models.CharField(max_length=30)),
                ('bgg', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Icon Legend', ' Icon Legend'), ('Turn Order', 'Turn Order')], max_length=20)),
                ('content', models.CharField(blank=True, max_length=20000)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geeks.game')),
            ],
        ),
        migrations.CreateModel(
            name='Legend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='images/')),
                ('description', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geeks.section')),
            ],
        ),
    ]
