# Generated by Django 4.1.5 on 2023-01-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='year',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
