# Generated by Django 4.1.5 on 2023-02-01 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extended', to='geeks.content')),
                ('image', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='geeks.image')),
            ],
        ),
    ]
