# Generated by Django 4.1.5 on 2023-01-31 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0002_game_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legend',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legends', to='geeks.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='geeks.game'),
        ),
    ]
