# Generated by Django 4.1.5 on 2023-02-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0002_extendedcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('legend', 'legend'), ('example', 'example'), ('description', 'description')], default='none', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='extendedcontent',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
