# Generated by Django 4.1.5 on 2023-02-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0003_content_type_alter_content_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={},
        ),
        migrations.RemoveField(
            model_name='content',
            name='order',
        ),
        migrations.AddField(
            model_name='extendedcontent',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendedcontent',
            name='type',
            field=models.CharField(choices=[('legend', 'legend'), ('example', 'example'), ('description', 'description')], default='legend', max_length=20),
            preserve_default=False,
        ),
    ]
