# Generated by Django 4.1.5 on 2023-01-31 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0003_alter_legend_section_alter_section_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='content',
        ),
    ]
