# Generated by Django 4.1.5 on 2023-02-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0004_alter_content_options_remove_content_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
