# Generated by Django 4.1.5 on 2023-02-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0008_alter_section_hashid'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='banner',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
