# Generated by Django 4.1.6 on 2023-02-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0009_game_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='direction',
            field=models.CharField(choices=[('flex-row', 'flex-row'), ('flex-col', 'flex-col')], default='flex-row', max_length=20),
        ),
        migrations.AlterField(
            model_name='content',
            name='text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='extendedcontent',
            name='direction',
            field=models.CharField(choices=[('flex-row', 'flex-row'), ('flex-col', 'flex-col')], default='flex-row', max_length=20),
        ),
        migrations.AlterField(
            model_name='extendedcontent',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
