# Generated by Django 4.1.5 on 2023-02-03 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0009_game_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendedcontent',
            name='name',
        ),
    ]
