# Generated by Django 4.1.6 on 2023-02-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0010_alter_content_direction_alter_content_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendedcontent',
            name='name',
        ),
        migrations.AlterField(
            model_name='extendedcontent',
            name='type',
            field=models.CharField(choices=[('legend', 'legend'), ('example', 'example'), ('description', 'description')], max_length=21),
        ),
    ]
