# Generated by Django 4.1.5 on 2023-02-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0010_remove_extendedcontent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='images/'),
        ),
    ]
