# Generated by Django 4.1.5 on 2023-02-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0011_alter_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='direction',
            field=models.CharField(choices=[('flex-row', 'flex-row'), ('flex-col', 'flex-col')], default='flex-row', max_length=20),
        ),
        migrations.AlterField(
            model_name='extendedcontent',
            name='direction',
            field=models.CharField(choices=[('flex-row', 'flex-row'), ('flex-col', 'flex-col')], default='flex-row', max_length=20),
        ),
    ]
