# Generated by Django 4.1.5 on 2023-02-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0012_alter_content_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='extendedcontent',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
